name: Build iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - name: Copy web assets
        run: npx cap copy ios

      - name: Install CocoaPods
        run: |
          cd ios/App
          pod install --repo-update

      - name: Build IPA
        run: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -archivePath $PWD/build/App.xcarchive archive
          mkdir -p export
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportPath $PWD/export -exportOptionsPlist ExportOptions.plist || true

      - uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/App/export/*.ipa
